### ISSUE TITLE
Choose a Normalizer/Reset

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#108]
## Is your feature request related to a problem? Please describe.

It was decided to use a normailizer/reset for the We Count website.

## Describe the solution you'd like

I believe either sanitize.css or a custom reset would work best.

## Describe alternatives you've considered

| Tools\Criteria             | Normalize or Reset | Load Time | Supported Browser                                                                                                           | Sass Availability | Memory Size      | License |
|----------------------------|--------------------|-----------|-----------------------------------|-------------------|------------------|------------------------------------|
| [Vanilla CSS Un-Reset](https://cssreset.com/scripts/vanilla-css-un-reset/)  *(no github page)*     | Reset              | n/a       | to be dertermined | yes               | 2 KB        | to be determined |
| [MiniReset.css](https://github.com/jgthms/minireset.css/)              | Reset              | n/a       | to be dertermined  | yes               | 690 bytes        | The MIT License (MIT) |
|[ sanitize.css](https://github.com/csstools/sanitize.css/)                | Normalize              | n/a       | Chrome (last 3), Edge (last 3), Firefox (last 3), Firefox ESR, Opera (last 3), Safari (last 3), iOS Safari (last 2), Internet Explorer 9+ | yes               | 9.3 KB           | Creative Commons Zero v1.0 Universal |
| [Reboot (part of Bootstrap v4)](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss) | Normalize          | n/a       | Chrome 45+, Firefox 38+, Opera 30+, Internet Explorer 10+, Edge 12+, iOS 9+, Safari 9+, Android 4.4+                                                                                                                        | no                | 11.2 KB          | The MIT License (MIT) |
| [Custom](https://medium.com/@elad/normalize-css-or-css-reset-9d75175c5d1e#4c86) *(no github page)*                  | Both               | n/a       | to be dertermined | yes               | to be determined | to be dertermined|
| [Normalize.css](https://github.com/necolas/normalize.css)              | Normalize          | n/a       |Chrome, Edge, Firefox ESR+, Internet Explorer 10+, Safari 8+, Opera  | yes               | 5.99 KB          | The MIT License (MIT) |

#### Normalizer vs Reset

CSS resets aim to remove all built-in browser styling. Standard elements like H1-6, p, strong, em, et cetera end up looking exactly alike, having no decoration at all. You're then supposed to add all decoration yourself.

Normalize CSS aims to make built-in browser styling consistent across browsers. Elements like H1-6 will appear bold, larger et cetera in a consistent way across browsers. You're then supposed to add only the difference in decoration your design needs.

*main take aways:*
* Normalize.css preserves useful defaults rather than "unstyling" everything
* Normalize.css corrects some common bugs that are out of scope for reset.css
* Normalize.css doesn't clutter your dev tools.
* Normalize.css is more modular.
* Normalize.css has better documentation.

#### Popularity comparison
https://www.npmtrends.com/normalize.css-vs-reset-css-vs-reset.css-vs-sanitize.css-vs-minireset.css-vs-reboot.css

#### Descriptions

https://css-tricks.com/reboot-resets-reasoning/#article-header-id-2

**Comment by jobara** [comment]
@TeddTech could you please expand on why you feel that "santize.css or a custom reset would work best". It's hard to tell from skimming the table why that suggestion was made. It might be worth writing up a more detailed description about them and listing out our requirements like we did for the [CSS frameworks](https://wiki.fluidproject.org/display/fluid/March+12%2C+2020%3A+Evaluate+the+necessity+of+using+a+CSS+framework).

**Comment by jobara** [comment]
Something to be aware of is that the makers of sanitize.css also make their own [csstools/normalize.css](https://github.com/csstools/normalize.css/blob/master/normalize.css). It appears that their version is a fork of [neoclass/normalize.css](https://github.com/necolas/normalize.css) see: https://github.com/csstools/normalize.css/issues/3 for a discussion on the differences. 

So that is another option to throw into the mix. 

csstools also makes [postcss-normalize](https://github.com/csstools/postcss-normalize) which can be used in conjunction with the browserslist config to remove unnecessary styling changes from either their normalize or sanitize css files.
