### ISSUE TITLE
Layout: responsive utilities

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#118]
## Is your feature request related to a problem? Please describe.

Build Sass mixins for responsive layouts. 

## Describe the solution you'd like

See https://github.com/platform-coop-toolkit/pinecone/blob/dev/src/assets/styles/mixins/_breakpoints.scss and https://github.com/platform-coop-toolkit/pinecone/blob/dev/src/assets/styles/functions/_breakpoints.scss.

## Describe alternatives you've considered

Not applicable.

## Additional context

Based on Bootstrap responsive utilities.

**Comment by cindyli** [comment]
Test main content columns with UIO to make widths flexible based on the screen size.
