### ISSUE TITLE
Images: support content images

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#137]
## Is your feature request related to a problem? Please describe.

We can improve our styling and display of content images from WordPress

## Describe the solution you'd like

We should support all content image orientations from WordPress.

## Describe alternatives you've considered

Not applicable.

## Additional context

- https://richtabor.com/gutenberg-image-alignments/

**Comment by TeddTech** [comment]
Views Post 11: https://deploy-preview-148--wecount.netlify.com/views/test-post-for-views-11

<img width="1100" alt="Screen Shot 2020-04-06 at 2 11 22 PM" src="https://user-images.githubusercontent.com/25180846/78605545-9b632f80-7810-11ea-9c4c-c204ac850011.png">

The caption is not aligned with the image

**Comment by greatislander** [comment]
Specs from @lliskovoi:

Max image width is 790px, aspect ratio is 16:9.
