### ISSUE TITLE
Auto generate navigation menus based on the API response

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#170]
## Is your feature request related to a problem? Please describe.

Right now, main navigation menus on the header and the footer are hardcoded.

## Describe the solution you'd like

The main navigation menu should be auto generated based on the response from the WordPress API: https://wecount-dev.inclusivedesign.ca/wp-json/wp/v2/pages

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by greatislander** [comment]
Pages can be assigned a `menu_order` attribute in WordPress. It's an integer value. See the "Order" field in the right column (exposed in the REST API here: https://wecount-cms.inclusivedesign.ca/wp-json/wp/v2/pages/118):

<img width="1114" alt="Screen Shot 2020-04-09 at 3 25 27 PM" src="https://user-images.githubusercontent.com/605361/78942173-5cceae80-7a76-11ea-8959-fa32f996e3a1.png">

A strategy for the navigation could be using this field to indicate which pages should be included in the menu, with the following logic:

1. Only include pages in the menu if they have a `menu_order` value > 0.
2. Sort the pages by `menu_order` value in ascending order.

**Comment by greatislander** [comment]
This would mean that News and Views would need to be appended to the end of the menu, assuming that the other pages appeared first (they don't correspond to pages in WordPress). Maybe this idea still needs work.

**Comment by greatislander** [comment]
https://wecount-cms.inclusivedesign.ca/wp-json/wp/v2/pages?order=asc&orderby=menu_order
