### ISSUE TITLE
Image of cards on the main page disappears in different themes

### ISSUE THREAD

**Issue by chosww** [inclusive-design/wecount.inclusivedesign.ca#1700]
## Describe the bug

Using the website in different themes provided by UIO removes image of cards on the main page. From what I see, classes from UIO removes background-image. 

## To Reproduce

1. Go to the home page
2. Scroll down to where the cards are, and see images are properly displayed
3. Change the themes of the page using UIO
4. See the images on the cards are gone

## Expected behavior

Each card image should have different color set for different themes. 

## Screenshots

<img width="1329" alt="Screen Shot 2024-02-20 at 10 50 16 AM" src="https://github.com/inclusive-design/wecount.inclusivedesign.ca/assets/22668696/730f9a00-df32-4583-b24a-a4f0f942c550">

**Comment by greatislander** [comment]
See: https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/650

I think we can address this but would be ideal to use SVG colour filters as seen on https://weavly.org rather than creating 7 (?) variations of each image.

**Comment by chosww** [comment]
Oh, I didn't see this issue was surfaced before, but yeah that's exactly the solution I was telling Uttara about.
