### ISSUE TITLE
Add UIO

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#171]
## Is your feature request related to a problem? Please describe.

UIO is not integrated into the WeCount website.

## Describe the solution you'd like

The documentation of integrating UIO: https://docs.fluidproject.org/infusion/development/tutorial-userInterfaceOptions/UserInterfaceOptions.html

We should pull it in from NPM and use a distribution.

If possible, we should use UIO from Antranig's latest infusion branch: https://github.com/fluid-project/infusion/pull/972 rather than the infusion master branch.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by jobara** [comment]
Regarding the one from Antranig's branch, it's useful if you don't want the default UIO set of preferences. However, if the current standard set is all that is needed, a dev branch from master may be a better choice for now.

**Comment by cindyli** [comment]
@TeddTech, the source code of an UIO integration demo can be found [here](https://github.com/fluid-project/infusion/blob/master/demos/uiOptions/index.html). It directly uses [the UIO component `fluid.uiOptions.prefsEditor`](https://github.com/fluid-project/infusion/blob/master/demos/uiOptions/index.html#L79), which is more straightforward than [the preferences framework demo](https://github.com/fluid-project/infusion/blob/master/demos/prefsFramework/index.html) I showed you the other day.

**Comment by TeddTech** [comment]
## User Interface Options
The following features were tested in the chrome browser. Future works will have these features being tested in Mozilla(Firefox) browser*
**text-size** ✅ : Works as expected

**text style**  ✅: Works as expected

**line spacing** ✅: Works as expected

**contrast** ❌: Social media buttons are not visible for the second option

**table of contents** ✅: Works as expected

**enhance inputs** ✅ : Works as expected

**Comment by cindyli** [comment]
@TeddTech, just a reminder that don't forget to test UIO with responsive design mode. Sometimes increasing text size or line space will break the layout on smaller screens.

**Comment by greatislander** [comment]
@TeddTech Social media icon issue will be addressed in #136.
