### ISSUE TITLE
Views posts with no tags show an empty tags area

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#177]
## Describe the bug

If a views post does not have any tags assigned to it, the tags area will be displayed but does not have any tags.

## To Reproduce

1. Remove tags from a post, e.g. "Continuing Our Work During COVID-19".
2. Visit the post on the Nuxt site.
3. Scroll down to the Tags area.
4. Observe that the title of the section ("Tags") is shown but no tags are present.

## Expected behavior

If no tags are assigned, the tags area is hidden.

## Screenshots

Not applicable.

## Additional context

Not applicable.

**Comment by cindyli** [comment]
Resolved by https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/190
