### ISSUE TITLE
Error page is thrown when querying "" in search

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#19]
## Describe the bug

When querying "" in the search bar the error page is thrown.
Only effects some pages.

## To Reproduce

1. Go to search
2. query ""

## Expected behavior

should return all pages as results

**Comment by jobara** [comment]
@TeddTech when you say, 

> Only effects some pages.

do you have a list of which pages are affected? Or is it a certain "type" of page this is affected.
