### ISSUE TITLE
Update card for "learn" page

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#191]
## Is your feature request related to a problem? Please describe.

Follow [the figma design](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website) to:

1. Update icons for tiles on the home page;
2. Add a tile for the Learn page.

**Comment by gmanas813** [comment]
can i work on it?

**Comment by cindyli** [comment]
@gmanas813, thanks for you interest in this issue. It has been addressed by https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/193/files.
