### ISSUE TITLE
Contributing link in the README is broken

### ISSUE THREAD

**Issue by jobara** [inclusive-design/wecount.inclusivedesign.ca#197]
## Describe the bug

The link in the README to the contributor guide is broken

## To Reproduce

1. Go to '[README.md](https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/dev/README.md)'
2. Click on the 'contributing' link in the first paragraph under 'Getting Started'
3. The browser returns a 404 page

## Expected behavior

Should open the [contributing](https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/dev/.github/CONTRIBUTING.md) document

## Additional context

It looks like the default URLs for files contained within `.github` are different than those for other parts of the repo.

**Comment by greatislander** [comment]
@jobara it's because we haven't merged into master. This will be fixed with the 1.1 release.

**Comment by jobara** [comment]
@greatislander, thanks. I hadn't realized that `dev` is the default branch in GitHub. I wonder if we could switch it to a relative path so that we don't have to link to a different branch to access the file.

**Comment by greatislander** [comment]
I tried and there doesn't appear to be a way to use a relative link :(

**Comment by jobara** [comment]
We use relative links in the infusion-docs repo. ( example: https://github.com/fluid-project/infusion-docs/blob/master/src/documents/Builder.md ). I suppose there might be a difference for the .github files, but not sure.

**Comment by greatislander** [comment]
Got it working!
