### ISSUE TITLE
Confirm UIO Integration

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#219]
## Is your feature request related to a problem? Please describe.

Confirm that UIO can override styles.

## Describe the solution you'd like

1. Test the site with the [UIO+ Chrome extension](https://chrome.google.com/webstore/detail/ui-options-plus-uio%20/okenndailhmikjjfcnmolpaefecbpaek).
2. Document any issues.

## Describe alternatives you've considered

Alternative approaches to be determined after testing.

## Additional context

[Preferences Framework](https://docs.fluidproject.org/infusion/development/tutorial-prefsFramework/CreatingAPrefsEditor.html)

**Comment by TeddTech** [comment]
## User Interface Options Plus
The following features were tested in the chrome browser. Future works will have these features being tested in Mozilla(Firefox) browser*
**Zoom** ✅ : Works as expected

**Character Spacing**  ✅: Works as expected

**Word Spacing** ✅: Works as expected

**Line Spacing** ✅: Works as expected

**Syllables** ✅: Works as expected

**Contrast** ✅ : Works as expected

**Right-click to select** ❌: Not working as expected

**Selection Highlight** ✅: Works as expected

**Text to Speech** ✅: Works as expected

**Reading Mode** ❌: Not working as expected 

**Table of Content** ✅: Works as expected

**Enhance Inputs** ✅: Works as expected

**Youtube Captions** ❌: No youtube videos on the current version of the site to test with.

**Comment by jobara** [comment]
Right-click to select, Reading Mode, and YouTube Captions are all only available in UIO+ and not in the UIO you'd integrate into a site. However, we'll probably eventually add Reading Mode / Simplification into UIO but not sure the implementation will be the same.

**Comment by greatislander** [comment]
@TeddTech I think this can be closed in lieu of #171.
