### ISSUE TITLE
Outstanding Issues for Eleventy Website

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#220]
## Is your feature request related to a problem? Please describe.

- Side Menu for View posts needs to be implemented
- Gridview for search needs to be implemented
- When on first and last page pagination is not centred (this may be done purposely).

## Describe the solution you'd like

Fix outstanding issues.

## Describe alternatives you've considered

Alternative approaches to be determined after fixing.

## Additional context

N/A

**Comment by cindyli** [comment]
@TeddTech, the issue https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/214 I'm working on should solve the 2nd problem `Gridview for search needs to be implemented`.

**Comment by greatislander** [comment]
>  Side Menu for View posts needs to be implemented

I think it is implemented. @TeddTech, can you create a test post on the dev CMS (wecount-dev.inclusivedesign.ca) and see if it works for you?

> When on first and last page pagination is not centred (this may be done purposely).

Can you open a PR to address this? @TeddTech

**Comment by TeddTech** [comment]
> > Side Menu for View posts needs to be implemented
> 
> I think it is implemented. @TeddTech, can you create a test post on the dev CMS (wecount-dev.inclusivedesign.ca) and see if it works for you?
> 
> > When on first and last page pagination is not centred (this may be done purposely).
> 
> Can you open a PR to address this? @TeddTech

Okay, got it.

**Comment by TeddTech** [comment]
> > Side Menu for View posts needs to be implemented
> 
> I think it is implemented. @TeddTech, can you create a test post on the dev CMS (wecount-dev.inclusivedesign.ca) and see if it works for you?
> 
> > When on first and last page pagination is not centred (this may be done purposely).
> 
> Can you open a PR to address this? @TeddTech

@greatislander There is already two test post on the WordPress dev site that should be showing the side menu. Links for them are below:

- https://deploy-preview-207--wecount.netlify.app/views/test-views-post/

- https://deploy-preview-207--wecount.netlify.app/views/another-test-post/

The links above have `h2` tags in the content section but are not showing a side menu

**Comment by greatislander** [comment]
@TeddTech Okay— in that case, can you take a look at that too? Relevant code is in `/src/transforms/parse.js`.

**Comment by greatislander** [comment]
@TeddTech I'm closing this— please open a new issue for the views side menu.
