### ISSUE TITLE
Center Pagination

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#221]
## Describe the bug

When on first and last page pagination is not centred 

## To Reproduce

1. Go to Views page
2. Click on the first or last post
3. Scroll down to Pagination
4. See error (Pagination is not centred)

## Expected behavior

Pagination should always be centered

## Screenshots
**First Issue**
<img width="1440" alt="Screen Shot 2020-04-30 at 6 10 24 PM" src="https://user-images.githubusercontent.com/25180846/80773329-6fd11d80-8b0e-11ea-964f-f2ece92e9ec9.png">

**Second Issue**
<img width="1440" alt="Screen Shot 2020-04-30 at 6 10 01 PM" src="https://user-images.githubusercontent.com/25180846/80773319-69db3c80-8b0e-11ea-80be-3011e41e33f7.png">

## Desktop (please complete the following information):

- OS: macOS High Sierra
- Browser: chrome
- Version: 81.0.4044.122

**Comment by Neilblaze** [comment]
Please assisgn this task to me.

**Comment by Neilblaze** [comment]
I inspected the views page in three different browsers (Chrome, Firefox & Edge), but haven't found this bug till now. The class registered to the pagination .nav says that it's already centered.
![centred pagination for wecount inclusivedesign ca](https://user-images.githubusercontent.com/48355572/80803524-277a3400-8bd0-11ea-8eda-95c9b90c4f2b.JPG)


Morever, when I tried centering the block via <center>  tag, no change is observed!

[Path] - ./wecount.inclusivedesign.ca/pages/views/page/_num/index.vue

**Comment by cindyli** [comment]
Thanks for your interest in this project and offering help, @Neilblaze. We are in the midst of migrating from Nuxt platform in the `master` branch to [Eleventy](https://www.11ty.dev/) in [the `eleventy` branch](https://github.com/inclusive-design/wecount.inclusivedesign.ca/tree/eleventy). If you setup the website with the `eleventy` branch, the problem can be reproduced.

This is [the deploy preview](https://deploy-preview-207--wecount.netlify.app/views/) of the pull request https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/207 based off the `eleventy` branch. The problem can be seen here too.

**Comment by greatislander** [comment]
Fixed in ad38c85.
