### ISSUE TITLE
Side Menu for View Posts

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#222]
## Is your feature request related to a problem? Please describe.

Implement a side menu for view posts

## Describe the solution you'd like

Have the same side menu that on the site pages be on view posts as well

## Describe alternatives you've considered

N/A

**Comment by TeddTech** [comment]
@greatislander Do we want the side menu to include the Main title of the page?

<img width="587" alt="Screen Shot 2020-05-01 at 11 00 48 AM" src="https://user-images.githubusercontent.com/25180846/80828973-15ca6980-8b9b-11ea-939b-606c02e449ac.png">

**Comment by greatislander** [comment]
@TeddTech Please make your pull request against the `eleventy` branch when you submit it.

**Comment by TeddTech** [comment]
> @TeddTech Please make your pull request against the `eleventy` branch when you submit it.

Will do

**Comment by TeddTech** [comment]
> @greatislander Do we want the side menu to include the Main title of the page?
> 
> <img alt="Screen Shot 2020-05-01 at 11 00 48 AM" width="587" src="https://user-images.githubusercontent.com/25180846/80828973-15ca6980-8b9b-11ea-939b-606c02e449ac.png">

@greatislander Do we want the side menu to include the Main title of the page?

**Comment by greatislander** [comment]
I don't think so, but I would check with @lliskovoi.
