### ISSUE TITLE
Improve tag archive generation

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#227]
## Is your feature request related to a problem? Please describe.

Right now the tag archive pages can't be paginated as they are themselves paginated instances of the `tags` collection. (See: https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/dev/src/tagsItem.njk.) However, we may be able to add tags to news and views collection items directly using the computed data features in Eleventy 0.11 (see: https://www.11ty.dev/docs/data-computed/).

## Describe the solution you'd like

Add tags directly to News and Views collection items, allowing us to generate static tag archives that are paginated the same way.

## Describe alternatives you've considered

We could rethink the tag archive layouts and continue to use the current system, but we wouldn't be able to paginate the data.

## Additional context

Not applicable.

**Comment by cindyli** [comment]
A couple of other issues with the tag archive page to be address with this re-work:

1. The page title is empty. It should be "Tag (Smart Cities) | We Count".

2. No layout difference for news items and views items. Views items should display the placeholder image and author.

**Comment by greatislander** [comment]
Eleventy 0.11.0 is out now: https://github.com/11ty/eleventy/releases/tag/v0.11.0

**Comment by cindyli** [comment]
After some experiments, the new "computed data" feature doesn't help with creating the pagination for the "tags" page. The pagination is added by manually calculating pagination objects and posts data page by page at generating `collections.tags`.
