### ISSUE TITLE
UIO enhance inputs shrinks size of header nav fonts

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#234]
## Is your feature request related to a problem? Please describe.

The size of the header nav fonts decrease when enhance inputs is turned on

## Describe the solution you'd like

Header nav fonts should increase when enhance input uio is turned on like other links

## Describe alternatives you've considered

N/A

## Additional context

<img width="1440" alt="Screen Shot 2020-05-12 at 9 19 27 PM" src="https://user-images.githubusercontent.com/25180846/81770890-680e6300-9496-11ea-9dd8-2f93a08f04f8.png">

<img width="1440" alt="Screen Shot 2020-05-12 at 9 19 46 PM" src="https://user-images.githubusercontent.com/25180846/81770879-604ebe80-9496-11ea-930c-22dff5600fa4.png">

**Comment by cindyli** [comment]
The decision for this issue at today's check-in: when "enhance inputs" is enabled, do not decrease the font size of navigation links but keep the original size .

**Comment by TeddTech** [comment]
@cindyli `Enactors.css` in infusion uses `!important` on this element the font size for for enhance inputs so looks like I also have to use an `!important` when correcting this issue

**Comment by TeddTech** [comment]
@cindyli `Enactors.css` in infusion uses `!important` on the font size for for enhance inputs so it looks like I also have to use an `!important` when correcting this issue

**Comment by TeddTech** [comment]
@cindyli `Enactors.css` in infusion uses `!important` on the font size for enhance inputs so looks like I also have to use an `!important` when correcting this issue

**Comment by TeddTech** [comment]
@cindyli `Enactors.css` in infusion uses `!important` on the `font-size` for enhance inputs so looks like I also have to use an `!important` when correcting this issue

**Comment by cindyli** [comment]
> @jobara @cindyli `Enactors.css` in infusion uses `!important` on the `font-size` for enhance inputs so looks like I also have to use an `!important` when correcting this issue

It makes sense to use `!important` in this case.
