### ISSUE TITLE
Improve sidebar navigation

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#235]
## Is your feature request related to a problem? Please describe.

In a call last week, we discussed some desired improvements to the sidebar navigation:

1. It should be sticky (i.e. it should remain in the viewport as the page/post scrolls).
2. It should include a link to the page/post title (h1) so that users can jump back to the top when scrolled to the bottom of a page/post.
3. The hierarchy (h1 through h2) should be reflected in the type styles.
4. The currently active section should be highlighted in the sidebar as per designs - the thicker side bar.
5. The aria-labelledby attribute of the sidebar points to an empty span which needs some text (I think @lliskovoi suggested "secondary navigation").

## Describe the solution you'd like

Resolve above issues. For sticky positioning, consider: https://css-tricks.com/position-sticky-2/

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by TeddTech** [comment]
Look into [scroll events](https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event)
