### ISSUE TITLE
Add more UIO preferences

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#240]
## Is your feature request related to a problem? Please describe.

The importance order of other UIO preferences to be added:
1. Simplify
2. Text to speech
3. Syllables
4. Word spacing (optional)
5. Letter spacing (optional)

## Describe the solution you'd like

The infusion preferences framework demo is an example for adding these extra preferences: [infusion/demos/prefsFramework/](https://github.com/cindyli/infusion/blob/UIO-WeCount/demos/prefsFramework/index.html)

**Comment by jobara** [comment]
@cindyli do you have any plans/details for how the simplify feature should work for the wecount site. I believe I mentioned that simplify isn't a "real" preference yet, so we'll need to add it. I can probably migrate some code from [uio-plus](https://github.com/fluid-project/uio-plus/blob/master/src/js/content_scripts/simplification.js) but we should make sure it's going to work as needed.

**Comment by cindyli** [comment]
@jobara, my understanding from yesterday's meeting is, the simplify will show `<main>` element that contains UIO table of content and the main article. It will hide the side menu. Right now, only "About" and "Inclusion Challenges" pages have side menus.

@lliskovoi, can you please confirm? Thanks.

**Comment by jobara** [comment]
What about the navigation and search?

**Comment by cindyli** [comment]
Good point, @jobara. Also, shall the logo section and the footer not be shown too?

Eventually on the "views" page, there will be another search for views items only as well as a filtering section. What to do with the search and filtering on this page?

@lliskovoi, would it be easier to create a couple of mockups to clarify the design for the simplify preference? Thanks.

**Comment by cindyli** [comment]
The UIO syllables panel has been added at https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/247 and merged at https://github.com/inclusive-design/wecount.inclusivedesign.ca/commit/3793dd2d881b580b313f958ff5b5ccf4fb79dfd2

**Comment by cindyli** [comment]
Closed as separate issues are created for implementing each preference:

#272: simplify
#271: text to speech
#247: syllables
