### ISSUE TITLE
Pressing "Enter" key on UIO "line space" input box breaks UIO

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#248]
## Describe the bug

Pressing "Enter" key on UIO "line space" input box breaks UIO

## To Reproduce

1. Open UIO;
2. click into "line space" input box
3. doesn't matter to change or not change the value;
4. hit "enter" key

Problem: All panels in UIO disappear and leave a grey blank page.

Then,
1. Click "hide preferences", UIO closes;
2. Click "show preferences", UIO doesn't open and is broken. In firefox or safari, this error is thrown in the dev tool console: 
```
Ignoring call to invoker updateModel of component  
Object { typeName: "fluid.uiEnhancer", id: "1xjwwss1-439", lifecycleStatus: "destroyed", destroy: fabricateDestroyMethod()
, options: {…}, events: {…}, fluid_prefs_enactor_tableOfContents: {…}, fluid_prefs_enactor_enhanceInputs: {…}, fluid_prefs_enactor_contrast: {…}, fluid_prefs_enactor_textFont: {…}, … }
  which has been destroyed
``` 

Hitting "enter" in the line space field breaks UIO. 

## Expected behavior

The changed line space value applies to the website and UIO stays intact.

## Screenshots

After hitting "ENTER":
<img width="1383" alt="Screen Shot 2020-05-28 at 5 29 29 PM" src="https://user-images.githubusercontent.com/572877/83195840-e27eea00-a108-11ea-98a0-420deda908f6.png">

## Additional context

This issue cannot be reproduced in [the infusion UIO demo](https://build.fluidproject.org/infusion/demos/uiOptions/) or [the infusion prefs framework demo](https://build.fluidproject.org/infusion/demos/prefsFramework/).

All UIO panels are wrapped in a `<form>` element. The further investigation shows this problem is because hitting "Enter" triggers the form submission event. This event doesn't get triggered with infusion demos but with WeCount website.

**Comment by jobara** [comment]
@cindyli and @TeddTech, I did some more investigation on this, and it appears that the problem is that an [Implicit Submission](https://www.w3.org/TR/html53/sec-forms.html#implicit-submission) is occurring. In this case, it is happening because there is only 1 text input in the form. If there is an additional input type that block implicit submission, then it will not occur. That is why in the UI Options and Prefs Framework demos this issue doesn't arise; there are at least 2 text inputs in the demos.

There are various solutions to the issue including but not limited to the following:

- add an explicit submit button that is hidden
- add additional input fields ( for example adding the word or letter spacing preferences )
- prevent the default action on the form
- etc.

**Comment by cindyli** [comment]
Cool. @jobara. I just figured out the same reason by reading [this thread](https://stackoverflow.com/questions/4196681/form-not-submitting-when-pressing-enter). I've successfully reproduced the same issue with UIO demos. I think the root of the problem should be fixed in the preference framework rather than here. Filing a infusion JIRA now.

**Comment by TeddTech** [comment]
@jobara  @cindyli Awesome so once we add the other panels this issue will no longer persist?

**Comment by cindyli** [comment]
BTW, @jobara, adding "letter spacing" or "letter spacing" will introduce the same issue as "text size": the nav menus at both edges could be pushed out of the viewport with small screens. That's why they are optional on the importance list.

@TeddTech, there are only 3 other panels having text input fields: text size, letter spacing and word spacing. Unfortunately, they all create the problem described above.

**Comment by jobara** [comment]
@cindyli at some point we'll need to think of ways to address those issues. While screen zooming is something that the browser, there are no such alternatives for letter and word spacing. As you come across these integration issues, it's probably worthwhile to document them. In the future we should document some ideas for possible solutions for integrating these preferences while painting the design. It may be that the content needs to extend beyond the borders of the screen/window. Kind of like on a mobile device when you pinch-to-zoom and have to pan around to see everything.

**Comment by cindyli** [comment]
Good point, @jobara.

I've filed 2 JIRA against UIO and preferences framework:
[FLUID-6597](https://issues.fluidproject.org/browse/FLUID-6507): Pressing "Enter" breaks UIO;
[FLUID-6598](https://issues.fluidproject.org/browse/FLUID-6508): Texts being pushed out of viewport with text size, letter spacing and word spacing preferences.

Hopefully the 2nd JIRA could be the starting point for discussions.

**Comment by cindyli** [comment]
Closed as this issue will be address in the infusion preferences framework. See [FLUID-6597](https://issues.fluidproject.org/browse/FLUID-6507).
