### ISSUE TITLE
Hyphenate words displayed on multiple lines

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#256]
## Is your feature request related to a problem? Please describe.

When a single word is broken into multiple lines, add hyphen on word break to indicate that is one single word.

## Describe the solution you'd like

See [the comment below](https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/256#issuecomment-640875527) of the research result.

## Steps to reproduce the issue

1. Go to [https://dev--wecount.netlify.app/views/project-we-count-evaluates-torontos-quayside-master-innovation-and-development-plan/](https://dev--wecount.netlify.app/views/project-we-count-evaluates-torontos-quayside-master-innovation-and-development-plan/);
2. Click "show preferences" button to open UIO;
3. Change these UIO settings: set text style to "Open Dyslexic", enable "enhance inputs" and "syllables";
4. See the screenshot below, the word "development" is broken into 2 lines.

**Expected**: A hypen(-) should be added on the word break to indicate that is one single word: developmen-t

## Screenshot
<img width="198" alt="Screen Shot 2020-07-30 at 11 56 06 AM" src="https://user-images.githubusercontent.com/572877/88945471-07ecb900-d25c-11ea-98f2-0eb5f616c327.png">

**Comment by cindyli** [comment]
Research results:
1. "overflow-wrap" and "word-break" don't help. "hyphens" helps by adding a hyphen when a word is broken up into a separate line;

2. The use of "hyphens":
* "hyphens: manual" is not practical as the same word may or may not be broken into separate lines or is broken at the different letter depending on the screen size;
* "hyphens: auto" does add hyphens but different browsers handle this attribute differently. Firefox does the best job by firstly displaying a long word into a different line. If the word doesn't fit into a entire new line, firefox breaks this word into a separate line and adds a hyphen to join the word. However in Chrome, a long word won't be attempted to be displayed in a separate line but always displayed with other words and a hyphen is added to join the long word. From the screenshot below taken in Chrome, the first pic without adding "hyphens: auto" is better.

In Chrome, before adding "hyphens: auto": 
<img width="174" alt="Screen Shot 2020-06-08 at 4 28 36 PM" src="https://user-images.githubusercontent.com/572877/84077676-b6375900-a9a5-11ea-81d9-6af3ad578e76.png">

In Chrome, after adding "hyphens: auto":
<img width="171" alt="Screen Shot 2020-06-08 at 4 23 56 PM" src="https://user-images.githubusercontent.com/572877/84077699-bdf6fd80-a9a5-11ea-8664-f614b69b59e7.png">

In the discussion with @lliskovoi and @uttaraghodke, it's decided adding "hyphens: auto" is better than not having hyphens to join words even though it's not perfect.

At the moment, this issue only happens in the dev site with the use of the word "development". We'll hold off on adding the overkill solution of "hyphens: auto" until it's needed in the production site.

**Comment by jobara** [comment]
sorry, accidentally closed the issue when I meant to cancel a comment.

**Comment by cindyli** [comment]
@Raunaksingh100, if you'd like to, please work on this issue. Make sure to follow the development process documented in [the contributing guide](https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/dev/.github/CONTRIBUTING.md).

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100, if you'd like to, please work on this issue. Make sure to follow the development process documented in [the contributing guide](https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/dev/.github/CONTRIBUTING.md).

In this we only need to add to this 

Hpyens : auto;

???

**Comment by cindyli** [comment]
> In this we only need to add to this
> 
> Hpyens : auto;
> 
> ???

@Raunaksingh100 you need experiment and test.

**Comment by Raunaksingh100** [comment]
According to me i just reduce the font- size to 2.0rem after doing this , this issue Solved and doing this of font -size to 2.0rem 
dosenot affect the website  **and this bug fixed in all the phones i noticed carefully ** no need of """""hyphens"""
see in the screenshot given below  -----
###desktop--
![desltop](https://user-images.githubusercontent.com/65535360/88957141-123e9f80-d2bc-11ea-8b0f-cee4ee6f7563.PNG)

###mobile 
![in mobile view](https://user-images.githubusercontent.com/65535360/88957161-18cd1700-d2bc-11ea-93a7-9fcc618658ea.PNG)

**Comment by TeddTech** [comment]
@Raunaksingh100 Which phone screen size is used in the mobile screen shot provided? And did you test all screen sizes including the Galaxy Fold.

Another area of the website that spills into multiple lines that should not is the We Count email in the footer.

<img width="390" alt="Screen Shot 2020-07-30 at 11 02 17 AM" src="https://user-images.githubusercontent.com/25180846/88957719-2fd81e80-d254-11ea-895e-3d02632e54c2.png">

**Comment by cindyli** [comment]
@Raunaksingh100 changing font size is not an ideal solution as the length of words is unpredictable.

BTW, could you use proper English, punctuation and markdown syntax so your comments are easier to understand. Thanks.

**Comment by Raunaksingh100** [comment]
> According to me i just reduce the font- size to 2.0rem after doing this , this issue Solved and doing this of font -size to 2.0rem
> dosenot affect the website **and this bug fixed in all the phones i noticed carefully ** no need of """""hyphens"""
> see in the screenshot given below ----
> 
> ### Desktop--
> ![desltop](https://user-images.githubusercontent.com/65535360/88957141-123e9f80-d2bc-11ea-8b0f-cee4ee6f7563.PNG)
> 
> ### Mobile
> ![in mobile view](https://user-images.githubusercontent.com/65535360/88957161-18cd1700-d2bc-11ea-93a7-9fcc618658ea.PNG)
> 
> ### after the changing of the font size you can see the size of h1 still same as earlier,,,,,,
> ### avoid hyphens in h1 is doesnot look goods
> ### this my point of view i hope you like it

in my localhost i cannot find this page in fact they only show this see in this screenshot given below
![not same](https://user-images.githubusercontent.com/65535360/89001755-be15d880-d318-11ea-8511-ea2278e8ecd2.PNG)

plz help

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 Which phone screen size is used in the mobile screen shot provided? And did you test all screen sizes including the Galaxy Fold.
> 
> Another area of the website that spills into multiple lines that should not is the We Count email in the footer.
> 
> <img alt="Screen Shot 2020-07-30 at 11 02 17 AM" width="390" src="https://user-images.githubusercontent.com/25180846/88957719-2fd81e80-d254-11ea-895e-3d02632e54c2.png">


![now](https://user-images.githubusercontent.com/65535360/89095344-98590400-d3ea-11ea-866a-b52e2464f757.PNG)

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 Which phone screen size is used in the mobile screen shot provided? And did you test all screen sizes including the Galaxy Fold.
> 
> Another area of the website that spills into multiple lines that should not is the We Count email in the footer.
> 
> <img alt="Screen Shot 2020-07-30 at 11 02 17 AM" width="390" src="https://user-images.githubusercontent.com/25180846/88957719-2fd81e80-d254-11ea-895e-3d02632e54c2.png">

### i fixed this issue you can see in the screenshot below 

![fixed](https://user-images.githubusercontent.com/65535360/89100501-05818f00-d415-11ea-85b9-edf1c7f89bca.PNG)

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 Which phone screen size is used in the mobile screen shot provided? And did you test all screen sizes including the Galaxy Fold.
> 
> Another area of the website that spills into multiple lines that should not is the We Count email in the footer.
> 
> <img alt="Screen Shot 2020-07-30 at 11 02 17 AM" width="390" src="https://user-images.githubusercontent.com/25180846/88957719-2fd81e80-d254-11ea-895e-3d02632e54c2.png">

### i fixed this 2.part of this  issue you can see in the screenshot below ---

### screenshot 
![fixed](https://user-images.githubusercontent.com/65535360/89126994-c41ddc00-d507-11ea-9278-0769f8ab4a2e.PNG)

### and i also working on 1 part of this  issue .......

**Comment by cindyli** [comment]
@uttaraghodke, @lliskovoi, the email address "wecount@inclusiv­edesign.ca" on the footer could be displayed on 2 lines when displayed on a small screen such as Galaxy Fold.

One solution is to add a hyphen(-) at the word break as in the screenshot:
<img width="151" alt="Screen Shot 2020-08-04 at 10 50 24 AM" src="https://user-images.githubusercontent.com/572877/89309762-d1d77c80-d641-11ea-9162-7fa41ac4d66f.png">

However, this may mislead users that the email address has the hyphen in it: "wecount@inclusiv­-edesign.ca".

In order not to confuse users, another solution is not to hyphenate this email address when it's broken into 2 lines but leaving the word as is. Other words should continue to be hyphenated when they are broken into multiple lines.

Please let us know your suggestion. Thanks.

**Comment by Raunaksingh100** [comment]
@cindyli  ### it not misleading to the users  Because we cannot use hphens in our user names see in the screenshot given below

![see](https://user-images.githubusercontent.com/65535360/89312375-d24d3300-d694-11ea-82ca-5100a9527b79.PNG)

**Comment by cindyli** [comment]
@Raunaksingh100 hyphens are allowed in domain names.

**Comment by uttaraghodke** [comment]
> @uttaraghodke, @lliskovoi, the email address "wecount@inclusiv­edesign.ca" on the footer could be displayed on 2 lines when displayed on a small screen such as Galaxy Fold.
> 
> One solution is to add a hyphen(-) at the word break as in the screenshot:
> <img alt="Screen Shot 2020-08-04 at 10 50 24 AM" width="151" src="https://user-images.githubusercontent.com/572877/89309762-d1d77c80-d641-11ea-9162-7fa41ac4d66f.png">
> 
> However, this may mislead users that the email address has the hyphen in it: "wecount@inclusiv­-edesign.ca".
> 
> In order not to confuse users, another solution is not to hyphenate this email address when it's broken into 2 lines but leaving the word as is. Other words should continue to be hyphenated when they are broken into multiple lines.
> 
> Please let us know your suggestion. Thanks.

@cindyli I agree. Let got with option 2 and not hyphenate.

**Comment by Raunaksingh100** [comment]
as the mentor can you tell me the  html file of this issue here the screenshot of the html file which i cannot find in SRC FOLDER  

![this file](https://user-images.githubusercontent.com/65535360/89438055-f6c51000-d765-11ea-8eef-be39bf37fdfd.PNG)

with the little help of mentor i can easily fixed this bug

**Comment by TeddTech** [comment]
> as the mentor can you tell me the html file of this issue here the screenshot of the html file which i cannot find in SRC FOLDER
> 
> ![this file](https://user-images.githubusercontent.com/65535360/89438055-f6c51000-d765-11ea-8eef-be39bf37fdfd.PNG)
> 
> with the little help of mentor i can easily fixed this bug
> plz help
> @TeddTech

The `src/transforms/parse.js` file creates this html element dynamically

**Comment by Raunaksingh100** [comment]
@TeddTech  thanks but in that folder there is no this "project we-count-evalutes-toronto"s-quayside-master-innovation-and
-development-plan""
plz help mentor

**Comment by TeddTech** [comment]
> @TeddTech thanks but in that folder there is no this "project we-count-evalutes-toronto"s-quayside-master-innovation-and
> -development-plan""
> plz help mentor

It pulls in that data from the WordPress headless CMS. Please read documentation

**Comment by Raunaksingh100** [comment]
@TeddTech  this bug only fixed by their html file which is coming from wordpress,,,
and who have rights access to  the data of wecount website in wordpress that person can fixed this  bug

beacuse in src folder there is no line like this """"" project we-count-evalutes-toronto"s-quayside-master-innovation-and
-development-plan""
this is only available in wordpress site 
thanks............

**Comment by cindyli** [comment]
The only occurence of this issue has been fixed by modifying the corresponding WordPress post with adding the soft hyphen.

Thanks for the contribution of using soft hyphens (`&shy;`), @Raunaksingh100.
