### ISSUE TITLE
SVGs change to default when switching contrast themes while enhance inputs is turned on

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#266]
## Describe the bug

SVGs switch to default attribute values when user is switching contrast themes while enhance inputs is turned on.

## To Reproduce

1. Go to mobile view (any mobile view will do)
2. Turn on enhance inputs UIO preference 
3. toggle through UIO contrast themes 
4. See error in brand svg and header search svg

## Expected behavior

The same svg attribute values should remain (except colour/contrast) when switching contrast themes while enhance inputs is turned on as before.

## Screenshots
<img width="471" alt="Screen Shot 2020-06-03 at 6 14 54 PM" src="https://user-images.githubusercontent.com/25180846/83705130-ef984f00-a5c8-11ea-9092-30bd3840909e.png">

## Additional context

N/A

**Comment by cindyli** [comment]
This issue is reproducible with the desktop view too.

**Comment by cindyli** [comment]
Fixed with the merge of #233.
