### ISSUE TITLE
Add UIO text-to-speech when the design is ready

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#271]
## Is your feature request related to a problem? Please describe.

Add UIO text-to-speech when the design is ready. The design will address:

* The text-to-speech button styles
* Where on the page should the “play” and “stop” buttons be shown
* What content should be read when the “play” button is pressed

cc: @lliskovoi, @uttaraghodke

## Additional context

The text-to-speech feature can be found in [the preferences framework demo](https://build.fluidproject.org/infusion/demos/prefsFramework/):

1. Open UIO;
2. Scroll horizontally to the text-to-speech panel;
3. Turn on and off the text-to-speech toggle button to get familiar with how text-to-speech works.

**Comment by Raunaksingh100** [comment]
@cindyli  can you review my pr for idrc PROJECT

**Comment by cindyli** [comment]
@Raunaksingh100, thanks for your interest in IDRC projects and I appreciate your help working on issues. 

Just a heads up, please post your requests or ask questions at where they belong to instead of randomly picking an issue ticket in a random project. For example, If you'd like to request someone's review on a pull request, comment on that pull request. If you have a question regarding a particular issue, ask at that issue ticket.

This will help to keep our repositories clean and organized. Your cooperation is much appreciated.

Regarding the pull request you requested my review. I never worked on that project and don't even know where to find its UX design. Moreover, @jobara has helped to [ping right reviewers](https://github.com/inclusive-design/idrc/pull/39#issuecomment-663042378) on that PR.

**Comment by Raunaksingh100** [comment]
can you review #346 of wecount projects

**Comment by cindyli** [comment]
Closed as there isn't an intention to add UIO text-to-speech feature.
