### ISSUE TITLE
Add LinkedIn link to social media links in footer

### ISSUE THREAD

**Issue by lliskovoi** [inclusive-design/wecount.inclusivedesign.ca#276]
## Is your feature request related to a problem? Please describe.

Currently there is no social media link to the We Count LinkedIn page. 

## Describe the solution you'd like

Add icon with link to LinkedIn page: https://www.linkedin.com/in/wecountproject/
Lisa will provide icon and different colour variations

**Comment by TeddTech** [comment]
@lliskovoi @cindyli Where can I find the resources for the LinkedIn icon?

**Comment by cindyli** [comment]
> @lliskovoi @cindyli Where can I find the resources for the LinkedIn icon?

@TeddTech @lliskovoi said she will get it ready tomorrow and let us know.
