### ISSUE TITLE
Fix html validation errors and warnings

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#302]
## Describe the bug

Run webpages through [W3C html validator](https://validator.w3.org/). The same set of 2 errors and 2 warnings are reported, which should be fixed

## To Reproduce

1. Go to [W3C html validator](https://validator.w3.org/);
2. In "Validate by URI" tab, enter "https://dev--wecount.netlify.app/" and click the "check" button;
3. The report as the attached screenshot is reported.

## Expected behavior

All issues causing errors and warnings should be fixed.

## Screenshots

<img width="849" alt="Screen Shot 2020-06-19 at 10 40 30 AM" src="https://user-images.githubusercontent.com/572877/85144916-d2df5680-b219-11ea-995e-050995b225a6.png">

**Comment by TeddTech** [comment]
I believe this issue can be closed now because the PR associated with (#303) it has been merged

**Comment by cindyli** [comment]
Good point, @TeddTech. 

This issue can be close as the PR #303 for fixing it has been merged.
