### ISSUE TITLE
Improve visual appearance of the website when the design is ready

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#322]
## Describe the bug

The font sizes for headings and side menus are too big in general.

**Comment by Raunaksingh100** [comment]
@cindyli  can i work on this issue??
and plz provide a screenshot for the better understanding...........

**Comment by uttaraghodke** [comment]
**Desktop Fonts:**
H1: font size: 50pt/3.125em | font weight: semi-bold
H2: font size: 35pt/1.9em | font weight: medium
H3: font size: 24pt/1.3em | font weight: bold
H4: font size: 18pt/1em | font weight: bold
Paragraph/Body: 18pt/1em | font weight: regular

![image](https://user-images.githubusercontent.com/66276957/87825898-f364f580-c845-11ea-8e4f-a7d9a31ddedd.png)

**Comment by uttaraghodke** [comment]
**Menu Bar:**

18pt/1em | font weight: bold

![image](https://user-images.githubusercontent.com/66276957/87826144-59517d00-c846-11ea-8bae-0f664081f946.png)

**Comment by uttaraghodke** [comment]
**Side Menu**

18pt/1em | font weight: bold (When selected), regular (when unselected)

![image](https://user-images.githubusercontent.com/66276957/87826232-843bd100-c846-11ea-96a8-bfb5c90e155d.png)

**Comment by TeddTech** [comment]
> **Menu Bar:**
> 
> 18pt/1em | font weight: bold
> 
> ![image](https://user-images.githubusercontent.com/66276957/87826144-59517d00-c846-11ea-8bae-0f664081f946.png)

Hey @uttaraghodke, quick confirmation. Is the weight supposed to be bold? This is not what is reflected in the image.

**Comment by TeddTech** [comment]
> > **Menu Bar:**
> > 18pt/1em | font weight: bold
> > ![image](https://user-images.githubusercontent.com/66276957/87826144-59517d00-c846-11ea-8bae-0f664081f946.png)
> 
> Hey @uttaraghodke, quick confirmation. Is the weight supposed to be bold? This is not what is reflected in the image.

Thank you for making the changes @uttaraghodke

**Comment by cindyli** [comment]
@uttaraghodke, could you update your comments to use one single unit `px` so that it's consistent with what's in the figma design. For example, modify `35pt/2.5em` to `35px`.

In terms of the use of `em`:
1. It's better to use `rem` than `em` because `rem` is relative to the font size of the root element `<html>` while `em` is relative to the font size of the parent container, which makes `rem` easier to calculate and less variable;
2. The conversions from `px` to `em` in your comment are not consistent across. `35pt/2.5em` uses `16` as the base size while `35pt/1.9em` uses `18` as the base size.

That's why I feel to be less confusing and more consistent with the Figma design, it's probably better to use one single unit `px` and match what's in Figma.

Let me know what you think. Thanks.

**Comment by uttaraghodke** [comment]
@cindyli , I have updated them

**Comment by uttaraghodke** [comment]
Tiles Desktop and Mobile: 18px | medium

![image](https://user-images.githubusercontent.com/66276957/88200526-40fdab80-cc14-11ea-81e6-e3a72e273edf.png)
