### ISSUE TITLE
Remove Google Analytics tracking

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#323]
## Is your feature request related to a problem? Please describe.

The website now has both Google Analytics tracking and IDRC Mamoto tracking. Vera has confirmed their reports are quite similar. We can now only use IDRC Mamoto tracking for privacy.

**Comment by TeddTech** [comment]
@cindyli I believe this issue has been resolved in PR #324 and can now be removed.
