### ISSUE TITLE
Improve the Hewlett funding information on the footer

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#342]
## Describe the bug

Increase the size of the Hewlett logo and remove the link in the text.

Css values decided at today's meeting:

```
width: 18rem; 
height: 5rem; 
padding-bottom: 0
```

**Comment by Raunaksingh100** [comment]
can you help me i am facing this problem in this project ###linebreal error [ IN  WINDOWS]
i doesnot change anything but why i am facing this see in the screenshot given below for the better understanding 

![we count err](https://user-images.githubusercontent.com/65535360/88382275-bf4d7f80-cdc5-11ea-9ba5-315897d7e38d.PNG)
