### ISSUE TITLE
Improve "Tags Filters" text on Views landing page

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#347]
## Describe the bug

1. Change the text “Tags Filters” to “Filters” or “Search Filters”;
2. The font size of “tags filters” should be smaller.

## To Reproduce

1. The text can be viewed on [https://dev--wecount.netlify.app/views/](https://dev--wecount.netlify.app/views/).

**Comment by cindyli** [comment]
@uttaraghodke and @lliskovoi, could you comment when you have answers to questions in this issue ticket? Thanks.

**Comment by uttaraghodke** [comment]
@cindyli Can we make that H3?

**Comment by cindyli** [comment]
@uttaraghodke, yes, we can make it look like h3 but continue to use <h2> tag in order to meet [WCAG 2 success criterion for heading levels](https://www.w3.org/TR/WCAG20-TECHS/G141.html).

Regarding to the other question, what text do you prefer to change to? Thanks.

**Comment by uttaraghodke** [comment]
@cindyli can we style it to look like a h3? And also, lets call it 'Search Filters'

I will also make this change in figma

**Comment by cindyli** [comment]
> @cindyli can we style it to look like a h3? And also, lets call it 'Search Filters'
> 
Yes, no problem. Thanks for the reply, @uttaraghodke.

**Comment by Raunaksingh100** [comment]
@cindyli  can i work on this issue ??
