### ISSUE TITLE
Create the new workshop comments page

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#350]
## Is your feature request related to a problem? Please describe.

Clicking a workshop on the "Initiatives" page redirects to a new workshop page that shows the detail of this workshop and a comment area where users can post new comments and view existing comments.

The design for this page can be found on [the Figma for the "Initiatives" page](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website?node-id=1881%3A3695).

## Some implementation points
* Verify name and comment values at the client side: Name and Comment values are required
* When the "post a comment" button is clicked, send a POST request to a Netlify function endpoint at the server side with a payload of comment contents to save
    * The server side Netlify function will be implemented using #370
* Page style

**Comment by Raunaksingh100** [comment]
can you tell me why y left the irc channel @cindyli

**Comment by gtirloni** [comment]
@Raunaksingh100 thanks for your contributions so far, we really appreciate it.

That being said, if you want to work on the WeCount project, you'll need to coordinate with the team that's already working on it first. They can help you understand how you could get involved.

We have designers working on the project that have put together a visual design for the site and that's being implemented in phases by the project team. You'll need to coordinate with the team so your work does not overlap with what others are already working on. Does that make sense?

Finally, if you could quickly write down how you plan to help the projects, which areas interest you the most, etc, that would also help us in figuring out what type of work could be assigned to you. You have submitted some PRs for CSS styling, is that what you're most interested in working on?

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 thanks for your contributions so far, we really appreciate it.
> 
> That being said, if you want to work on the WeCount project, you'll need to coordinate with the team that's already working on it first. They can help you understand how you could get involved.
> 
> We have designers working on the project that have put together a visual design for the site and that's being implemented in phases by the project team. You'll need to coordinate with the team so your work does not overlap with what others are already working on. Does that make sense?
> 
> Finally, if you could quickly write down how you plan to help the projects, which areas interest you the most, etc, that would also help us in figuring out what type of work could be assigned to you. You have submitted some PRs for CSS styling, is that what you're most interested in working on?

Iam  interested in styling the page as well as making the page of html .....

**Comment by cindyli** [comment]
> So can you provide we any work regarding this project
>
@Raunaksingh100 Let's have further conversation on IRC. I've pinged you there. BTW, I'm only on IRC during my work hours: 9-4:30 EST weekdays.
