### ISSUE TITLE
added the border radius to the elements of navbar  hover 

### ISSUE THREAD

**Issue by Raunaksingh100** [inclusive-design/wecount.inclusivedesign.ca#351]
## Is your feature request related to a problem? Please describe.
added the border radius to the elements of navbar while hovar
 see in the screenshot given below for the better understanding.......

## Describe the solution you'd like
just added the border radius ......

###screenshot before---
![now ft](https://user-images.githubusercontent.com/65535360/88759185-d73b4f80-d187-11ea-8d14-84c2c66de2a0.PNG)

### after
![now](https://user-images.githubusercontent.com/65535360/88759432-63e60d80-d188-11ea-8743-d14bb5b323ca.PNG)

here the link of my pr --------- https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/352
plz view and merged it i really want to ontribute this project...

## Additional context
@cindyli  plz merged  it i really want to contribute on this project
@jobara

**Comment by cindyli** [comment]
@Raunaksingh100 the website appearance is implemented based on [the wireframe](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website) designed by UX designers. The round border of this hover styling is not desired.

Would you be able follow [these steps](https://wiki.fluidproject.org/display/fluid/Get+Involved#GetInvolved-IRC) to join `fluid-work` channel? Please ping me (`cindyli`) when you hop on. We can have a conversation to discuss about how you can contribute to this project. Thanks.

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 the website appearance is implemented based on [the wireframe](https://www.figma.com/file/0lcLol3X5MmOXackT2YbHJ/WeCount-website) designed by UX designers. The round border of this hover styling is not desired.
> 
> Would you be able follow [these steps](https://wiki.fluidproject.org/display/fluid/Get+Involved#GetInvolved-IRC) to join `fluid-work` channel? Please ping me (`cindyli`) when you hop on. We can have a conversation to discuss about how you can contribute to this project. Thanks.

This is featured request to look improve the hover section

**Comment by cindyli** [comment]
@lliskovoi and @uttaraghodke, what do you think about @Raunaksingh100's suggestion?

**Comment by Raunaksingh100** [comment]
> @lliskovoi and @uttaraghodke, what do you think about @Raunaksingh100's suggestion?

Plz open this issue you can close this issue after the suggestion by @lliskovoi and @uttaraghodke
