### ISSUE TITLE
Align multiple lines of label texts in the search filter on the views landing page

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/wecount.inclusivedesign.ca#354]
## Describe the bug

Align multiple lines of label texts in the search filter on the views landing page.

## To Reproduce

1. Go to the views landing page, open "search filter";
2. Switch to mobile view;
3. Long labels are displayed in multiple lines and the lines below the first line start under the checkbox. See screenshot. 

## Expected behavior

Lines should be aligned. In the screenshot case, words "Master" and "Development" should be aligned.

## Screenshots

<img width="287" alt="Screen Shot 2020-07-30 at 5 24 20 PM" src="https://user-images.githubusercontent.com/572877/88976407-fd491880-d289-11ea-8509-f638f175b279.png">

**Comment by Raunaksingh100** [comment]
i fixed this issue can i make pr for this
![fixed checkbox](https://user-images.githubusercontent.com/65535360/89042576-c3007980-d364-11ea-8f06-a0bfa93db54c.PNG)

**Comment by Raunaksingh100** [comment]
i view this issue this issue shows inn many screen width fixing this is quite difficult but i fixed for all devices here the screenshoot given below

![try this](https://user-images.githubusercontent.com/65535360/89046550-bc750080-d36a-11ea-99e2-2b2b5b8851f1.PNG)
