### ISSUE TITLE
h1 break error

### ISSUE THREAD

**Issue by Raunaksingh100** [inclusive-design/wecount.inclusivedesign.ca#359]
## Is your feature request related to a problem? Please describe.

H1 error breaking when we use text-style with enable Syllabus ....

## Describe the solution you'd like

There is no need of adding ""hyphen:auto ""in this i added a  customized font-size (by their I'd),,,  
After  this I  won't get any bug , in any type of the screen 

**You can check the error **

1. Here the link direct link -

https://wecount.inclusivedesign.ca/views/journeys-through-the-digital-innovation-appendix-of-the-master-innovation-and-development-plan/

2. select the **OPEN DYSLEXIC** text-style with enable the syallbus feature you get this bug

### screenshot 

![error](https://user-images.githubusercontent.com/65535360/89003744-3337dc80-d31e-11ea-9f6c-f43ede19cf47.PNG)

## Additional context
I am working on this issue

### PLZ VIEW MY PR FOR BETTER UNDERSTANDING this works in all devices plz accept this idea its better then using hypens

**Comment by cindyli** [comment]
This ticket is a subset of #256. Closed.
