### ISSUE TITLE
images is getting blur in mobile view 

### ISSUE THREAD

**Issue by Raunaksingh100** [inclusive-design/wecount.inclusivedesign.ca#373]
## Describe the bug

The images is getting blur and are not responsive in the mobile view and this issue visible in majority types of devices

## To Reproduce

1. Go to 'https://wecount.inclusivedesign.ca/initiatives/'
2. Click on 'inspect the images'
3. changed  to 'any mobile screen this bug see '

### Screenshots before of 1--------
![1](https://user-images.githubusercontent.com/65535360/90499232-ec901200-e166-11ea-82e9-cd8dce115acd.PNG)

### before of 2------
![2](https://user-images.githubusercontent.com/65535360/90499319-04679600-e167-11ea-81ba-7dfc08818bf3.PNG)

### Screenshot after I fixed this bug
the image should me look like this the screenshot given below ----
![1](https://user-images.githubusercontent.com/65535360/90499812-a5eee780-e167-11ea-8ad2-7e93e5fe3018.PNG)

## Smartphone (please complete the following information):

- Device: [e.g. iPhone6, galaxy fold , motog4 Etc]

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by cindyli** [comment]
Closed as this issue has already been fixed by #367 and merged into the dev branch. See [the development deploy](https://dev--wecount.netlify.app/initiatives/) for the verification. This fix will be rolled out to the production site at the next release.
