### ISSUE TITLE
the Email link is gone to next line when we increase space and changes text-style in mobile 

### ISSUE THREAD

**Issue by Raunaksingh100** [inclusive-design/wecount.inclusivedesign.ca#381]
## Describe the bug
 the email link is gone to next line when we increase the space to """2""" and changed the text-style to """" verdana""" 
see in the screenshot for the better understanding
## To Reproduce

1. Go to 'https://wecount.inclusivedesign.ca/ '   or  'https://dev--wecount.netlify.app/'
2. chaned the text-style to "verdana" and add the space in it "2"
3. Scroll down to 'Footer'

### Screenshots ---
![issue](https://user-images.githubusercontent.com/65535360/91655870-b8571280-ead1-11ea-99a3-9e68fc610cd7.PNG)

## Smartphone (please complete the following information):

- Device: [e.g. galaxy fold]
- Browser [e.g. stock browser]

**Comment by Raunaksingh100** [comment]
### i am working on this issue and you can see this bug in both sites given below--
1. https://dev--wecount.netlify.app/
2. https://wecount.inclusivedesign.ca/

**Comment by cindyli** [comment]
@Raunaksingh100 as we've discussed before with our designer Uttara at #256, it's acceptable that the email gets wrapped into multiple lines.

Closed.

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 as we've discussed before with our designer Uttara at #256, it's acceptable that the email gets wrapped into multiple lines.
> 
> Closed.

But this bug comes in when we added spaces 
But my code fixed this
