### ISSUE TITLE
Add Pagination to Initiatives Page

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#383]
## Is your feature request related to a problem? Please describe.

Add pagination bar on the initiatives page for users to switch between pages when there are enough workshops to be displayed on multiple pages.

## Describe the solution you'd like

Add `pagination.njk` component to `initiatives.njk` page

## Describe alternatives you've considered

N/A

## Additional context

https://github.com/inclusive-design/wecount.inclusivedesign.ca/pull/378#discussion_r480313618

**Comment by cindyli** [comment]
We can hold off on implementing this feature until the number of workshops reaches 10. At the moment, the total number of workshops that will be held under WeCount project is unknown.

**Comment by TeddTech** [comment]
> We can hold off on implementing this feature until the number of workshops reaches 10. At the moment, the total number of workshops that will be held under WeCount project is unknown.

Okay was in the middle of adding dummy workshops to the WeCount_Dev Airtable for testing this issue but I can hold off this if you believe its best.

**Comment by cindyli** [comment]
The decision is not to add the pagination to the Initiatives page.
