### ISSUE TITLE
Pagination Text Overflow in Mobile View with

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#386]
## Describe the bug

When using some of the UIO fonts the text in the pagination component overflows when text is a 3 digit number.

## To Reproduce

1. Go to a web page with 100 or more paginated pages. For example  [Continuing Our work During Covid-19 article](https://dev--wecount.netlify.app//views/continuing-our-work-during-covid-19/) on the We Count development site
2. Turn on UIO "Verdana" font
3. Inspect page in a mobile view. For example iPhone X.
4. Scroll down to the pagination component
5. See error

## Expected behavior

Text in pagination component should not overflow

#### Example with "Verdana" font
<img width="392" alt="Screen Shot 2020-09-08 at 6 14 30 PM" src="https://user-images.githubusercontent.com/25180846/92543277-eb9b4f00-f1ff-11ea-82fe-f62ca9ff1766.png">

#### Example with "Open Dyslexic" font
<img width="348" alt="Screen Shot 2020-09-08 at 5 14 35 PM" src="https://user-images.githubusercontent.com/25180846/92543285-f35af380-f1ff-11ea-97aa-464bdb3d46dd.png">

## Additional context

N/A

**Comment by cindyli** [comment]
Fixed with the merge of the pull request #385.
