### ISSUE TITLE
Component: Header / NavBar

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#41]
<img width="579" alt="NavBar component (desktop)." src="https://user-images.githubusercontent.com/605361/74193786-3a0a5000-4c15-11ea-94fd-fadb87f91882.png">

<img width="150" alt="NavBar component (mobile)." src="https://user-images.githubusercontent.com/605361/74193888-6e7e0c00-4c15-11ea-8c5a-eb5500814501.png">

**Comment by TeddTech** [comment]
How do I toggle mobile navbar vs the desktop navbar?

**Comment by jobara** [comment]
@TeddTech you'll likely be using [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries). However, at this point are you just working on the markup structure, or also adding the CSS and JS? @greatislander any thoughts?

**Comment by greatislander** [comment]
@TeddTech Yes, as per @jobara's comment, this PR should only add the markup. CSS and interactivity will be added later.

**Comment by TeddTech** [comment]
I have been making separate components for the mobile display. So 2 components for each issue. One for desktop and one for mobile. Is this approach correct? or should I take a different one?

**Comment by greatislander** [comment]
There should be one component that adjusts itself for mobile or desktop as necessary. See: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

There will likely be some JavaScript requirements for some of these as well. But each item should be a single component.

**Comment by greatislander** [comment]
Let's discuss this afternoon @TeddTech.

**Comment by TeddTech** [comment]
Okay so for now, should my PR just contain the desktop version then?

**Comment by greatislander** [comment]
Yes.
