### ISSUE TITLE
Develop clear and consistent approach and documentation for uploaded assets

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#495]
## Is your feature request related to a problem? Please describe.

Once #494 is merged, all uploaded files will be stored in GitHub except for one video file. For larger files this isn't the best approach as serving (for example) videos from Netlify will impact our bandwidth, and binary files committed to git will always need to be downloaded on checkout.

## Describe the solution you'd like

We should store small images and documents in Git, but host larger assets elsewhere (e.g. NextCloud).

## Describe alternatives you've considered

An alternative is to use [Netlify Large Media](https://docs.netlify.com/large-media/overview/) to track media files in a storage service. This feature works seamlessly with [Netlify CMS](https://www.netlifycms.org/docs/netlify-large-media/).

## Additional context

Not applicable.

**Comment by jobara** [comment]
Another option would be to use our cachefly CDN storage for large media files. We currently use cachefly to host the community and design Crit recordings. However, you'll need to upload files with an sftp client.

**Comment by greatislander** [comment]
Our decision is to use Netlify Large Media based on previous usage statistics. This has been implemented in #494.
