### ISSUE TITLE
Confirm that User Interface Options can override component-level styles

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#5]
## Is your feature request related to a problem? Please describe.

As it's likely that we will be integrating User Interface Options (UIO) into this project, we need to confirm that UIO can override styles within Vue components.

## Describe the solution you'd like

1. Test the site with the [UIO+ Chrome extension](https://chrome.google.com/webstore/detail/ui-options-plus-uio%20/okenndailhmikjjfcnmolpaefecbpaek).
2. Document any issues.
3. If necessary, move component-level styles into global stylesheet, adhering as closely to [Vue best practices](https://vuejs.org/v2/style-guide/#Component-style-scoping-essential) as possible.

## Describe alternatives you've considered

Alternative approaches to be determined after testing.

## Additional context

- [Preferences Framework](https://docs.fluidproject.org/infusion/development/tutorial-prefsFramework/CreatingAPrefsEditor.html)

**Comment by jobara** [comment]
The [Working with UI Options](https://docs.fluidproject.org/infusion/development/tutorial-userInterfaceOptions/WorkingWithUserInterfaceOptions.html) documentation may also be helpful.

**Comment by greatislander** [comment]
cc: @TeddTech.

**Comment by TeddTech** [comment]
## User Interface Options Plus
The following features were tested in the chrome browser. Future works will have these features being tested in Mozilla(Firefox) browser*
#### Zoom ✅ :
Works as expected

#### Character Spacing ✅:
Works as expected

#### Word Spacing ✅:
Works as expected

#### Line Spacing ✅:
Works as expected

#### Syllables ✅:
Works as expected

#### Contrast ✅:
Works as expected

#### Right-click to select ✅:
Works as expected

#### Selection Highlight ✅:
Works as expected

#### Text to Speech ✅:
Works as expected

#### Reading Mode ❌:
Not working as expected - Broken (Not working at all)

#### Table of Content ❌:
Not working as expected - Some of the links created are broken

#### Enhance Inputs ✅:
Works as expected

#### Reading Mode ❌:
Not working as expected - Simply doesn't work
