### ISSUE TITLE
Homepage Card graphics missing in contrast themes

### ISSUE THREAD

**Issue by BlueSlug** [inclusive-design/wecount.inclusivedesign.ca#650]
## Describe the bug

The graphics for the four section cards on the homepage are missing when UIO contrast themes are active.

## To Reproduce

1. Go to the home page
2. Open UIO and activate a contrast theme
3. Scroll down to the four cards

## Expected behavior

The four cards should have graphics that comply with the contrast themes, similar to the logo in the header.

## Screenshots

<img width="885" alt="2021-07-12 wecount home card graphics missing in uio contrast themes" src="https://user-images.githubusercontent.com/547933/125369134-abd65400-e349-11eb-91a6-6bc37b46ce78.PNG">

## Additional context

No environment info is included as all users are affected.

This may not be a major issue, given that the majority of the meaning of each card is provided by the text which remains visible. If this is determined not to be an issue, this should be closed and have the `wontfix` label applied to it.

**Comment by cindyli** [comment]
This is not a bug. It's intentional to hide these background images on cards.

**Comment by BlueSlug** [comment]
Not an issue, then :)
