### ISSUE TITLE
Update codebase to reflect content changes

### ISSUE THREAD

**Issue by BlueSlug** [inclusive-design/wecount.inclusivedesign.ca#671]
## Is your feature request related to a problem? Please describe.

Recently, the site content was revised and several sections were renamed as follows:
| Previous name | New/Current name |
| ---------------- | ------------ |
| Views               | Initiatives   |
| Initiatives         | Events        |
| Learn               | Resources   |
| -           | Badges       |
| Challenges      | _[relocated]_   |

The URLs were not updated, and so all of the content is still available at its previous URLs, which may lead to some confusion.

## Describe the solution you'd like

The site URLs should be updated to reflect this change in content, especially considering the fact that one of the names (Initiatives) has been reassigned to a different set of content.

### An important caveat
The former _Views_ page should retain its previous URLs (`/views/...`) in addition to being available at `/initiatives/...`, since these pages are linked in event announcements and communications, and we would like to ensure these links remain functional.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by greatislander** [comment]
Resolved by #1677.
