### ISSUE TITLE
API: create tag archives statically

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/wecount.inclusivedesign.ca#90]
## Is your feature request related to a problem? Please describe.

Right now tags are loaded into the [VueX Store](https://nuxtjs.org/guide/vuex-store) and can be queried by visiting `/tags?s=<tagname>`. This means all the tag matching has to happen client side.

## Describe the solution you'd like

We should build archives for each tag during the generate step. So, for example, a list of posts tagged with `AI` could be retrieved from https://wecount.inclusivedesign.ca/wp-json/wp/v2/posts?tags=3, and the archives would be built at `/tags/ai/`.

## Describe alternatives you've considered

Not applicable.

## Additional context

Tag archives will need to be paginated.

**Comment by cindyli** [comment]
I will use this ticket to create static routes for more pages: /about, /inclusion-challenges, /news, /news/page/{pageNum}
