### ISSUE TITLE
Only Import Necessary Bulma folders

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#94]
## Is your feature request related to a problem? Please describe.

Importing the full Bulma framework would include some unwanted functionality (e.g. set class stylings).

After the We Count check-in on 03/10/20, it is decided to only make use of the layout and grid functionality of Bulma. Additional functionality will be added as/if needed.

## Describe the solution you'd like

changed `main.scss` from:

```
@import "~bulma"
```

to 

```
@import "bulma/sass/utilities/_all.sass";
@import "bulma/sass/grid/_all.sass";
@import "bulma/sass/layout/_all.sass";
```

starting at line 9

## Describe alternatives you've considered

not applicable.

## Additional context

http://versions.bulma.io/0.7.2/documentation/overview/modular/

**Comment by greatislander** [comment]
I'd recommend importing the reset as well. It will make styling consistently across different browsers more easily.

https://github.com/jgthms/bulma/blob/master/sass/base/minireset.sass
